global using System.Net.Http.Headers;
global using System.Text;
global using Microsoft.AspNetCore.Http;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Logging;
global using Newtonsoft.Json;
global using System.Runtime.CompilerServices;
global using System.Security.Cryptography;
global using System.Web;