global using DotNet8.POS.PointService.Models;
global using Microsoft.AspNetCore.Mvc;
global using DotNet8.POS.Shared.Models;
global using DotNet8.POS.Shared;
global using Microsoft.EntityFrameworkCore;
global using DotNet8.POS.PointService.Services;
global using Serilog;
global using System.Reflection;
global using DotNet8.POS.PointService.Data;
